gcn-mi: remove proc_dir_entry::owner
proc_dir_entry::owner was removed in commit 99b7623380
(proc 2/2: remove struct proc_dir_entry::owner).

Stop using it to fix the following build failure.

drivers/misc/gcn-mi.c: In function 'mi_probe':
drivers/misc/gcn-mi.c:213: error: 'struct proc_dir_entry' has no member named 'owner'

Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>